### ISSUE TITLE
Issue : Unable to install medspacy

### ISSUE THREAD

**Issue by MANISH007700** [medspacy/medspacy#128]
Hello MedSpacy Team, 
When I try running `pip install medspacy` on my windows 11 arc64 based machine, I get error as 
`Collecting pyrush
  Using cached PyRuSH-1.0.3.5.tar.gz (44 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error

        python setup.py egg_info did not run successfully.
        exit code: 1

        [13 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "G:\Users\Manish\AppData\Local\Temp\pip-wheel-xeccbc4v\quicksectx_5f923c3b9a5a425fb733c088b3cf3f6b\setup.py", line 50, in <module>
            ext_modules=cythonize(extensions, language_level=3, language='c++'),
          File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Build\Dependencies.py", line 970, in cythonize
            module_list, module_metadata = create_extension_list(
          File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
            for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
          File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
            raise ValueError(error_msg)
        ValueError: 'quicksect/quicksect.pyx' doesn't match any files
        Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['G:\\Users\\Manish\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'G:\\Users\\Manish\\AppData\\Local\\Temp\\tmpf_3glxtu', '--quiet', 'quicksectx']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "G:\Users\Manish\AppData\Local\Temp\pip-install-ji1n8ofx\pyrush_8c84e80b4101459d96a0faeed59b4933\setup.py", line 36, in <module>
          setup(
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 806, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
          return installer(requirement)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 877, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['G:\\Users\\Manish\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'G:\\Users\\Manish\\AppData\\Local\\Temp\\tmpf_3glxtu', '--quiet', 'quicksectx']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.`

Anyway to solve this ? 

When I do `pip list` -> I see medspacy, but when I import it, it says `No module named pyrush`. I tried installing it too, but couldn't do it. 

Error for installatio of PyRush 
`  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error

        python setup.py egg_info did not run successfully.
        exit code: 1

        [13 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "G:\Users\Manish\AppData\Local\Temp\pip-wheel-zl4i9ikq\quicksectx_fb84dedd31154e0abfc06ac570961e49\setup.py", line 50, in <module>
            ext_modules=cythonize(extensions, language_level=3, language='c++'),
          File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Build\Dependencies.py", line 970, in cythonize
            module_list, module_metadata = create_extension_list(
          File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
            for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
          File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
            raise ValueError(error_msg)
        ValueError: 'quicksect/quicksect.pyx' doesn't match any files
        Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['G:\\Users\\Manish\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'G:\\Users\\Manish\\AppData\\Local\\Temp\\tmp6hzdhp5z', '--quiet', 'quicksectx']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "G:\Users\Manish\AppData\Local\Temp\pip-install-4aq34s8b\pyrush_ea2f97c245a24a7ead4d269b4e2ea9e5\setup.py", line 36, in <module>
          setup(
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 806, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
          return installer(requirement)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 877, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "G:\Users\Manish\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['G:\\Users\\Manish\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'G:\\Users\\Manish\\AppData\\Local\\Temp\\tmp6hzdhp5z', '--quiet', 'quicksectx']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.`

Thanks

**Comment by abchapman93** [comment]
Hello!
I believe that the issue is that you are using Python 3.9. Some of our dependencies have not yet been updated to support 3.9. Could you try using an environment in 3.8 and see if that works?

**Comment by MANISH007700** [comment]
Hello @abchapman93 , thanks for the quick followup. 
I tried using py3.8 on my linux SSH server. Works like charm. 

I'll try to do the same thing on my local window machine, till then take care :)
