### ISSUE TITLE
Runtime error for overlapping span

### ISSUE THREAD

**Issue by jmugan** [medspacy/medspacy#182]
When I use TargetMatcher to try to overwrite a span, I get

```
Traceback (most recent call last):
  File "/home/jmugan/anaconda3/lib/python3.8/site-packages/medspacy/target_matcher/target_matcher.py", line 163, in __call__
    doc.ents += (span,)
  File "spacy/tokens/doc.pyx", line 762, in spacy.tokens.doc.Doc.ents.__set__
  File "spacy/tokens/doc.pyx", line 799, in spacy.tokens.doc.Doc.set_ents
ValueError: [E1010] Unable to set entity information for token 4 which is included in more than one span in entities, blocked, missing or outside.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jmugan/Dropbox/consulting/Billenote/billenote_exp/umls/medspacy_rules.py", line 84, in <module>
    doc = nlp(text)
  File "/home/jmugan/anaconda3/lib/python3.8/site-packages/spacy/language.py", line 1031, in __call__
    error_handler(name, proc, [doc], e)
  File "/home/jmugan/anaconda3/lib/python3.8/site-packages/spacy/util.py", line 1670, in raise_error
    raise e
  File "/home/jmugan/anaconda3/lib/python3.8/site-packages/spacy/language.py", line 1026, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "/home/jmugan/anaconda3/lib/python3.8/site-packages/medspacy/target_matcher/target_matcher.py", line 167, in __call__
    raise RuntimeWarning(
RuntimeWarning: The result ""reviewed"" conflicts with a pre-existing entity in doc.ents. This result has been skipped.
```
The code says that just the RuntimeWarning should be raised. But that's not what appears to be happening. Version 0.2.0 just had `pass` https://github.com/medspacy/medspacy/blob/0.2.0.0/medspacy/target_matcher/target_matcher.py.

Is this just my machine? (Linux) Does it work for anyone else and just give a warning?

**Comment by jmugan** [comment]
I think the problem is we are not there to catch the warning. Maybe it should be something like `warnings.warn("can't overwrite entity")`?

**Comment by jmugan** [comment]
If I comment out lines 167 through 170 of `target_matcher.py` and replace them with `pass` things works as before.

**Comment by FMelloMascarenhas-Cohere** [comment]
Came here to write exactly about this issue. I guess the author intended to just issue a warning, but it actually does stop the code from running. So it does not behave as a warning.

**Comment by mcapizzi-cohere** [comment]
+1

**Comment by mcapizzi-cohere** [comment]
Here's the trace after the `RuntimeWarning`:

```Exception has occurred: RuntimeWarning       (note: full exception trace is shown but execution is paused at: <module>)
The result ""does"" conflicts with a pre-existing entity in doc.ents. This result has been skipped.
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/medspacy/target_matcher/target_matcher.py", line 163, in __call__
    doc.ents += (span,)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/spacy/tokens/doc.pyx", line 750, in spacy.tokens.doc.Doc.ents.__set__
    self.set_ents(ent_spans, default=SetEntsDefault.outside)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/spacy/tokens/doc.pyx", line 787, in spacy.tokens.doc.Doc.set_ents
    raise ValueError(Errors.E1010.format(i=i))

During handling of the above exception, another exception occurred:

  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/spacy/tokens/doc.pyx", line 787, in spacy.tokens.doc.Doc.set_ents
    raise ValueError(Errors.E1010.format(i=i))
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/spacy/tokens/doc.pyx", line 750, in spacy.tokens.doc.Doc.ents.__set__
    self.set_ents(ent_spans, default=SetEntsDefault.outside)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/medspacy/target_matcher/target_matcher.py", line 163, in __call__
    doc.ents += (span,)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/medspacy/target_matcher/target_matcher.py", line 167, in __call__
    raise RuntimeWarning(
  File "/var/folders/lx/qnr2781n3qx9v5d__86cjt0r0000gs/T/ipykernel_45073/1402888536.py", line 38, in extract
    matches = self.matcher(doc)
  File "/var/folders/lx/qnr2781n3qx9v5d__86cjt0r0000gs/T/ipykernel_45073/805921840.py", line 2, in <module> (Current frame)
    matches = sample_extractor.extract(doc)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3373, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3194, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2995, in _run_cell
    return runner(coro)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2940, in run_cell
    result = self._run_cell(
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/michael.capizzi/opt/anaconda3/envs/medspacy1_0_0/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
```

**Comment by burgersmoke** [comment]
It looks like this was fixed just over a year ago.  Please re-open if I am wrong, but this commit was May 5, 2023 and has been merged into master long ago:

https://github.com/medspacy/medspacy/commit/ce17e94ed7cb6aa12319307f7b67c3d5ce95fa34
