### ISSUE TITLE
NER on loaded model from disk produces sentence boundary error

### ISSUE THREAD

**Issue by bhartm3** [medspacy/medspacy#192]
Hello I'm using the example from the README to 

1. create the example matcher rule
2. save the model to disk
3. load it
4. perform NER on the same text.

But I'm getting a sentence boundary error. Is this due to the missing `pyrush` pipeline or because of `spacy.load()`? This is the code (it is mostly from the readme):

```
import medspacy
import spacy
from medspacy.ner import TargetRule

# Load medspacy model
nlp = medspacy.load()
print(nlp.pipe_names)

text = """
Past Medical History:
1. Atrial fibrillation
2. Type II Diabetes Mellitus

Assessment and Plan:
There is no evidence of pneumonia. Continue warfarin for Afib. Follow up for management of type 2 DM.
"""

# Add rules for target concept extraction
target_matcher = nlp.get_pipe("medspacy_target_matcher")
target_rules = [
    TargetRule("atrial fibrillation", "PROBLEM"),
    TargetRule("atrial fibrillation", "PROBLEM", pattern=[{"LOWER": "afib"}]),
    TargetRule("pneumonia", "PROBLEM"),
    TargetRule("Type II Diabetes Mellitus", "PROBLEM",
              pattern=[
                  {"LOWER": "type"},
                  {"LOWER": {"IN": ["2", "ii", "two"]}},
                  {"LOWER": {"IN": ["dm", "diabetes"]}},
                  {"LOWER": "mellitus", "OP": "?"}
              ]),
    TargetRule("warfarin", "MEDICATION")
]
target_matcher.add(target_rules)

doc = nlp(text)

# according to https://github.com/medspacy/medspacy/issues/183 removing the pyrush pipeline
nlp.remove_pipe("medspacy_pyrush")
nlp.to_disk("./medmodel")
nlp2 = spacy.load("./medmodel")
print(nlp2.pipe_names)

doc2 = nlp2(text)
assert doc.ents == doc2.ents
```
produces:
```
['medspacy_pyrush', 'medspacy_target_matcher', 'medspacy_context']
Traceback (most recent call last):
  File "/Users/benedict/git/fachpraktikum2223/examples/medical/script.py", line 45, in <module>
    doc2 = nlp2(text)
  File "/Users/benedict/git/fachpraktikum2223/venv/lib/python3.9/site-packages/spacy/language.py", line 1031, in __call__
    error_handler(name, proc, [doc], e)
  File "/Users/benedict/git/fachpraktikum2223/venv/lib/python3.9/site-packages/spacy/util.py", line 1670, in raise_error
    raise e
  File "/Users/benedict/git/fachpraktikum2223/venv/lib/python3.9/site-packages/spacy/language.py", line 1026, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "/Users/benedict/git/fachpraktikum2223/venv/lib/python3.9/site-packages/medspacy/context/context.py", line 310, in __call__
    modifier = ConTextModifier(rule, start, end, doc, max_scope=self.max_scope)
  File "/Users/benedict/git/fachpraktikum2223/venv/lib/python3.9/site-packages/medspacy/context/context_modifier.py", line 54, in __init__
    self.__set_scope(doc)
  File "/Users/benedict/git/fachpraktikum2223/venv/lib/python3.9/site-packages/medspacy/context/context_modifier.py", line 146, in __set_scope
    full_scope_span = doc[self._start].sent
  File "spacy/tokens/token.pyx", line 469, in spacy.tokens.token.Token.sent.__get__
  File "spacy/tokens/span.pyx", line 424, in spacy.tokens.span.Span.sent.__get__
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: `nlp.add_pipe('sentencizer')`. Alternatively, add the dependency parser or sentence recognizer, or set sentence boundaries by setting `doc[i].is_sent_start`.
['medspacy_target_matcher', 'medspacy_context', 'medspacy_pyrush']

Process finished with exit code 1
```
On
```
medspacy 1.0.1
Python 3.9.6
```

**Comment by burgersmoke** [comment]
@jianlins  Any chance you could take a look since you are familiar with medspacy and sentence boundary stuff like PyRuSH and others?

**Comment by jianlins** [comment]
After you reload "nlp"
nlp2 = spacy.load("./medmodel")
you need to add the sentencizer back to the pipeline and set it as the first component:
nlp2.add_pipe("medspacy_pyrush", **first=True**)

**Comment by bhartm3** [comment]
Hello @jianlins unfortunately calling then `nlp2(text)` yields empty spans on the text. I would expect the spans to be the same before and after the save right?
