### ISSUE TITLE
Enable multiprocessing in all core components of medspaCy

### ISSUE THREAD

**Issue by abchapman93** [medspacy/medspacy#36]
The fastest way to process texts with spaCy is:
```python
docs = list(nlp.pipe(texts, n_process=2))
```

However, this raises an exception due to multiprocessing (see examples below). This was first reported in #34 

I think that fixing this requires implementing some serialization methods for custom components and classes being used in those components. SpaCy gives some [instructions about serialization methods](https://spacy.io/usage/saving-loading#serialization-methods), but we haven't yet taken the time to understand them in detail.

For this to be implemented, this line of code should run:

```python
import medspacy
nlp = medspacy.load("en_core_web_sm", enable="all")
texts = ["Hello, world!"]
docs = list(nlp.pipe(texts, n_process=2))
```

**Comment by abchapman93** [comment]
Here are a few examples of tracebacks using the different components.

With ConText:
```
Process Process-7:
Traceback (most recent call last):
  File “~/opt/anaconda3/envs/medspacy-37/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File “~/opt/anaconda3/envs/medspacy-37/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File “~/opt/anaconda3/envs/medspacy-37/lib/python3.7/site-packages/spacy/language.py", line 1172, in _apply_pipes
    sender.send([doc.to_bytes() for doc in docs])
  File “~/opt/anaconda3/envs/medspacy-37/lib/python3.7/site-packages/spacy/language.py", line 1172, in <listcomp>
    sender.send([doc.to_bytes() for doc in docs])
  File "doc.pyx", line 934, in spacy.tokens.doc.Doc.to_bytes
  File “~/opt/anaconda3/envs/medspacy-37/lib/python3.7/site-packages/spacy/util.py", line 661, in to_bytes
    serialized[key] = getter()
  File "doc.pyx", line 933, in spacy.tokens.doc.Doc.to_bytes.lambda10
  File “~/opt/anaconda3/envs/medspacy-37/lib/python3.7/site-packages/srsly/_msgpack_api.py", line 16, in msgpack_dumps
    return msgpack.dumps(data, use_bin_type=True)
  File “~/opt/anaconda3/envs/medspacy-37/lib/python3.7/site-packages/srsly/msgpack/__init__.py", line 40, in packb
    return Packer(**kwargs).pack(o)
  File "_packer.pyx", line 285, in srsly.msgpack._packer.Packer.pack
  File "_packer.pyx", line 291, in srsly.msgpack._packer.Packer.pack
  File "_packer.pyx", line 288, in srsly.msgpack._packer.Packer.pack
  File "_packer.pyx", line 264, in srsly.msgpack._packer.Packer._pack
  File "_packer.pyx", line 282, in srsly.msgpack._packer.Packer._pack
TypeError: can not serialize 'ConTextGraph' object
```

With the Sectionizer:
```
TypeError: can not serialize 'Section' object
```

With TargetMatcher (with added rules):
```
TypeError: can not serialize 'TargetRule' object
```

QuickUMLS does work, so we should perhaps look at QuickUMLS's implementation details.

**Comment by bwang482** [comment]
This what I get by running the same toy example with only `'sentencizer', 'target_matcher'`:

```
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-46-f279e7cd71d0> in <module>
      1 nlp1 = medspacy.load("en_core_web_sm", disable=['tagger', 'parser', 'ner', 'context'])
      2 texts = ["Hello, world!"]
----> 3 docs = list(nlp1.pipe(texts, n_process=2))

d:\bo\envs\medspacy\lib\site-packages\spacy\language.py in pipe(self, texts, as_tuples, n_threads, batch_size, disable, cleanup, component_cfg, n_process)
    827         original_strings_data = None
    828         nr_seen = 0
--> 829         for doc in docs:
    830             yield doc
    831             if cleanup:

d:\bo\envs\medspacy\lib\site-packages\spacy\language.py in _multiprocessing_pipe(self, texts, pipes, n_process, batch_size)
    880         ]
    881         for proc in procs:
--> 882             proc.start()
    883 
    884         # Cycle channels not to break the order of docs.

d:\bo\envs\medspacy\lib\multiprocessing\process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

d:\bo\envs\medspacy\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

d:\bo\envs\medspacy\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

d:\bo\envs\medspacy\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     87             try:
     88                 reduction.dump(prep_data, to_child)
---> 89                 reduction.dump(process_obj, to_child)
     90             finally:
     91                 set_spawning_popen(None)

d:\bo\envs\medspacy\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

PicklingError: Can't pickle <function <lambda> at 0x000002671EDD79D8>: attribute lookup <lambda> on medspacy._extensions failed
```

**Comment by bwang482** [comment]
Is there any plan on enabling multiprocessing for medspacy? Thanks!

**Comment by MichalMalyska** [comment]
@bwang482 This requires making all components serializable, I will have time to contribute more after mid-April, so that sounds about right for start of the project.

**Comment by nicoloesch** [comment]
Is there any update on this issue? 

Furthermore, I think the issue extends beyond only multiprocessing but also saving and loading of `Doc` objects. Currently, if one utilises `TragetRule`, one cannot save the Docs using `DocBin` to file and reload them without getting different results. In my case, `is_negated` is at least lost and I am sure other attributes are as well.

**Comment by jianlinshi** [comment]
This has been resolved in latest version. 

import medspacy

if __name__ == '__main__':
    # Load with minimal components to avoid serialization issues
    nlp = medspacy.load()
    texts = ["The patient is now admitted to the cardio unit. Monitoring for chest pain and SOB."]
    # Use a single process for Windows compatibility
    docs = list(nlp.pipe(texts, n_process=1))
    print(len(list(docs[0].sents)))

**Comment by bwang482** [comment]
Great thanks @jianlinshi !!
